project_id = "zupuxlrtixhfnbuhxhum"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_manual_linking = false
enable_signup = true
enable_anonymous_users = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[edge_runtime]
enabled = true
ip_version = "ipv4"

[functions.search-run]
verify_jwt = true

[functions.search-quick]
verify_jwt = true

[functions.crm-add-contact]
verify_jwt = true

[functions.dashboard-summary]
verify_jwt = true

[functions.send-notification]
verify_jwt = false

[functions.crm-pipelines]
verify_jwt = true

[functions.crm-deals]
verify_jwt = true

[functions.crm-deal-move]
verify_jwt = true

[functions.crm-activities]
verify_jwt = true

[functions.crm-seed-pipeline]
verify_jwt = true

[functions.crm-create-pipeline]
verify_jwt = true

[functions.crm-add-from-search]
verify_jwt = true